name: shoto
version: 0.0.0.1
license: MIT
license-file: LICENSE
maintainer: mushin.hudoushin@gmail.com
author: Hikaru KONDO
synopsis: Shoto polyhedral compiler executable
category: Compilers

# extra-lib-dirs:
#   - /usr/local/cuda/lib64
#
# extra-libraries:
#   - cudart
#   - cuda
#   - nvrtc
#   - stdc++

dependencies:
  - base >= 4.19.1.0

language: GHC2024

library:
  source-dirs: src
  dependencies:
    - bytestring
    - process
    - unix
    - containers
    - mtl
  ghc-options: -Wall

tests:
  shoto-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
      - hspec-discover
    dependencies:
      - hspec
      - process
      - shoto
      - bytestring
      - containers
    ghc-options: -Wall
